networks:
  research-network:
    driver: bridge
    ipam:
      config:
        - subnet: $NET_SUBNET

services:
  research-index:
    build: .
    ports:
      - "8000:8000"
    networks:
      - research-network
    depends_on:
      - memgraph
    restart: unless-stopped

  memgraph:
    image: memgraph/memgraph:latest
    ports:
      - $MG_PORT:$MG_PORT
      - $MG_PORT_ALT:$MG_PORT_ALT
    networks:
      research-network:
        ipv4_address: $MG_HOST
    volumes:
      - mg_lib:/var/lib/memgraph
      - mg_log:/var/log/memgraph
    healthcheck:
      test: ["CMD", "curl", "-f", "http://{$MG_HOST}:{$MG_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 4G
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - research-network
    depends_on:
      - research-index
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  memgraph-lab:
    image: memgraph/lab:latest
    ports:
      - "3000:3000"
    networks:
      - research-network
    depends_on:
      - memgraph
    environment:
      - MEMGRAPH_HOST=$MG_HOST
      - MEMGRAPH_PORT=$MG_PORT
    restart: unless-stopped

volumes:
  mg_lib:
  mg_log: