services:
  research-index:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ri_log:/var/log/research_index.log
    environment:
      MG_HOST: memgraph
      MG_PORT: '7687'
      LOG_LEVEL: "DEBUG"
    depends_on:
      - memgraph
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: .
          target: .

  memgraph:
    image: memgraph/memgraph:latest
    ports:
      - 7687:7687
      - 7444:7444
    volumes:
      - mg_lib:/var/lib/memgraph
      - mg_log:/var/log/memgraph
    command: ["--log-level=TRACE"]
    healthcheck:
      test: ["CMD-SHELL", "echo 'RETURN 0;' | mgconsole || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 4G
    restart: unless-stopped

volumes:
  mg_lib:
  mg_log:
  mg_etc:
  ri_log: