name: Trigger auto deployment for research-index

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ development ]
    paths:
    - '**'
    - '.github/workflows/research-index-AutoDeployTrigger-e28b75b7-c869-4c24-ae9a-34f7c9ff21be.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RESEARCHINDEX_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RESEARCHINDEX_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RESEARCHINDEX_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: hub.docker.com
          registryUsername: ${{ secrets.RESEARCHINDEX_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RESEARCHINDEX_REGISTRY_PASSWORD }}
          containerAppName: research-index
          resourceGroup: ccg_research_index
          imageToBuild: hub.docker.com/research-index:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


